### ISSUE TITLE
Please fix this

### ISSUE THREAD

**Issue by mpereira96** [itsgaryk/bot#1]
![image](https://user-images.githubusercontent.com/16920897/103364850-a9e82a00-4ab6-11eb-960c-f8ad020e6977.png)
Disgusting low case letter at the start of the sentence, please change this.

Also remove `isFinite` check because there is no need for it and doesn't allow me to break the script and have fun.

**Comment by itsgaryk** [comment]
His @mpereira96 

Thank you for raising this.

The issue you have mentioned has now been resolved in the latest build. Should you encounter any further issues please let me know.

**Comment by LukeTPerry** [comment]
https://github.com/itsgaryk/bot/blob/ba839937571e02edd6c1df8f080cceae95acb13b/index.js#L95

This needs reopening as the original issue has not been addressed
