### ISSUE TITLE
Offensive comment left in by lazy developer

### ISSUE THREAD

**Issue by LukeTPerry** [itsgaryk/bot#2]
https://github.com/itsgaryk/bot/blob/c52e9a44294d7fe0e6ad83a4785e4597759a0be3/index.js#L19

Please can you remove comments before comitting code

**Comment by itsgaryk** [comment]
Hi @LukeTPerry 

Thank you for raising this.

I have combed through the comb and have identified the problematic line.

This has now been removed in the latest build.
